# Generated by Django 2.1 on 2019-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_recognition', '0002_auto_20190629_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercondition',
            name='user',
        ),
        migrations.AddField(
            model_name='usercondition',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
