# Generated by Django 2.1 on 2019-06-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stress_recognition', '0006_face'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Face',
            new_name='Photo',
        ),
    ]
