# Generated by Django 2.1 on 2019-06-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_recognition', '0008_auto_20190629_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='faces'),
        ),
    ]
