# Generated by Django 2.1 on 2019-06-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_recognition', '0010_photo_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='predicted',
            field=models.IntegerField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usercondition',
            name='predicted',
            field=models.IntegerField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
