# Generated by Django 2.1 on 2019-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_recognition', '0011_auto_20190630_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='predicted',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usercondition',
            name='predicted',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
